# Copy these entries into Streamlit Cloud's Secrets manager
BINANCE_API_KEY = "wZ6FSa9DEeeHLpnPZ3wCcnTqcfs8gYf7L4IBHYByEOTNxIXTZGef52NDWT7ehtKy"
BINANCE_API_SECRET = "iFe98RyFjgtDEqSpWU0Ikrao1iGF4joEsUshBVl8xxrYCFZANf2t0RGK1wjoOauK"
TELEGRAM_BOT_TOKEN = ""
TELEGRAM_CHAT_ID = ""
